/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const DEFAULT_POLICIES = [
  {
    title: "Privacy Policy",
    slug: "privacy-policy",
    content: `# Privacy Policy
Last updated: ${new Date().toLocaleDateString()}

This Privacy Policy describes how Bennie Tay Studio ("we", "us", or "our") collects, uses, and handles your data when you use our AI-driven Website-as-a-Service (WaaS) platform (the "Service").

## 1. Information Collection and Use
We collect several different types of information for various purposes to provide and improve our Service to you.

- **Personal Data:** While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). This includes, but is not limited to: Email address, First and last name, Phone number, and Business address.
- **Usage Data:** We may also collect information on how the Service is accessed and used ("Usage Data"). This may include information such as your computer's IP address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, and other diagnostic data.
- **AI Training Disclosure:** We use third-party AI providers (including Google Gemini). While we configure our API calls to opt-out of data training where possible, you acknowledge that your inputs are processed by third-party systems outside our direct control.

## 2. Tracking & Cookies Data
We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with small amount of data which may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.

## 3. Data Processing & Third-Party Service Providers
We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, or to perform Service-related services. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.

## 4. User as Data Controller (GDPR/CCPA Compliance)
If you use Bennie Tay Studio to build websites that collect data from your own end-users, **you are the Data Controller** and we are the Data Processor. You are strictly responsible for:
- Providing your own Privacy Policy to your end-users.
- Ensuring compliance with GDPR, CCPA, or other local jurisdictional laws.
- Managing data deletion requests from your end-users.
We disclaim all liability for your failure to comply with privacy regulations on your generated websites.

## 5. Security of Data
The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.

## 6. Disclosure of Data
We may disclose your Personal Data in the good faith belief that such action is necessary to:
- To comply with a legal obligation.
- To protect and defend the rights or property of Bennie Tay Studio.
- To prevent or investigate possible wrongdoing in connection with the Service.
- To protect the personal safety of users of the Service or the public.`,
  },
  {
    title: "Terms of Service",
    slug: "terms-of-service",
    content: `# Terms of Service
Last updated: ${new Date().toLocaleDateString()}

By accessing or using Bennie Tay Studio (the "Service"), you agree to be bound by these Terms of Service. This is a legally binding agreement.

## 1. AI Output Liability & "AS-IS" Disclaimer
The Service generates websites, copy, and code using Artificial Intelligence ("AI Output").
- **NO WARRANTY OF ACCURACY:** AI can "hallucinate" or generate incorrect, biased, or harmful content. Bennie Tay Studio makes no guarantee regarding the accuracy or fitness for purpose of any AI Output.
- **USER AUDIT OBLIGATION:** You MUST manually review every word, image, and line of code generated by the system before publishing. By publishing any content, you assume 100% legal responsibility for that content.
- **THIRD-PARTY INFRINGEMENT:** AI models may occasionally generate content similar to existing copyrighted works. You are responsible for performing necessary trademark and copyright cleared checks.

## 2. Indemnification & Hold Harmless
To the maximum extent permitted by law, you agree to defend, indemnify, and hold harmless Bennie Tay Studio, its founder, employees, and affiliates from and against any and all claims, damages, liabilities, losses, costs, or expenses (including reasonable legal fees) arising from:
- Your use of the Service.
- Any content you publish using the Service.
- Your violation of any third-party right, including intellectual property or privacy rights.
- Any business loss or regulatory fine incurred through your use of AI-generated assets.

## 3. Limitation of Liability
IN NO EVENT SHALL BENNIE TAY STUDIO BE LIABLE FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL, RELIANCE, OR SPECIAL DAMAGES, OR FOR LOST PROFITS, SAVINGS, OR DATA, REGARDLESS OF THE FORM OF ACTION (WHETHER IN CONTRACT, TORT, INCLUDING NEGLIGENCE, OR OTHERWISE), EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

THE TOTAL CUMULATIVE LIABILITY OF BENNIE TAY STUDIO FOR ANY CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY YOU TO BENNIE TAY STUDIO IN THE SIX (6) MONTHS IMMEDIATELY PRECEDING THE CLAIM.

## 4. Prohibited Uses
You agree not to use the Service to generate content for:
- Fraudulent activities, spam, or phishing.
- Promoting hate speech, violence, or illegal substances.
- Impersonating any person or entity.
- Any purpose that violates local, national, or international law.

## 5. Subscriptions & Payments
Subscriptions are billed in advance. All sales are final. No refunds are provided for partial months of service or for unused accounts. We reserve the right to change our pricing at any time.

## 6. Mandatory Arbitration & Class Action Waiver
Any dispute arising from these Terms shall be resolved through binding arbitration in Singapore. YOU AGREE TO WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.

## 7. Modifications to Terms
We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes your acceptance of the new terms.`,
  },
];
